#!/bin/bash
# Skript kysib kasutajalt ees- ja perekonnanime ning tervitab teda.

echo -n "Sisesta oma ees- ja perekonnanimi: "
read eesnimi perenimi
echo "Sinu eesnimi on $eesnimi ja perekonnanimi $perenimi."
