#!/bin/bash
# Skript v2ljastab lause, mis on kokku liidetud erinevatest muutujatest.

aasta=2021
president="Alar Karis"
lause_keskosa=". aastal valiti Eesti presidendiks "

lause="${aasta}${lause_keskosa}${president}"
echo $lause

